### ISSUE TITLE
The vault token is logged as INFO

### ISSUE THREAD

**Issue by sundbry** [mywordpress-io/caddy-vault-storage#3]
The vault token is being logged at INFO level!

Example:

```
{"level":"info","ts":1700070148.4857008,"logger":"tls","msg":"cleaning storage unit","description":"&{0xc000000e40 {https://vault.mydomain.net:8200 REDACTED_VAULT_TOKEN_here     kv caddy true <nil> <nil> }}"}
```

**Comment by kmott** [comment]
Interesting, what version of Caddy are you using, and how are you building the plugin?  Can you show me your Caddy config, and command you are using to start Caddy?

**Comment by sundbry** [comment]
Hi @kmott, you can build my same image here using the Dockerfile: https://github.com/gnomatic-cloud/caddylb

I don't have my Caddyfile at hand, but its roughly 

{ 
  storage vault "https://vault” {
   token "secret”
   ...
   }
}

**Comment by sundbry** [comment]
Come to think of it, this is possibly a side-effect of my changes in [PR #2](https://github.com/mywordpress-io/caddy-vault-storage/pull/2).

**Comment by kmott** [comment]
Okay, let me take a look at the MR, and make some adjustments, and I'll get back to you in a bit.

**Comment by kmott** [comment]
> Hi @kmott, you can build my same image here using the Dockerfile: https://github.com/gnomatic-cloud/caddylb
> 
> I don't have my Caddyfile at hand, but its roughly
> 
> { storage vault "[https://vault”](https://vault%E2%80%9D) { token "secret” ... } }

@sundbry I cannot find your Caddyfile in that repo, please paste the full Caddyfile here so I can reproduce your problem.

**Comment by kmott** [comment]
I was able to find a Caddyfile and reproduce the problem.  Closing this in favor of tracking the real issue in #2
